In [1]:
import os

# 获取当前工作目录
current_dir = os.getcwd()
print("当前工作目录：", current_dir)
 
# 切换到上一层目录
parent_dir = os.path.dirname(current_dir)
os.chdir(parent_dir)
print("切换后的目录：", parent_dir)

当前工作目录： /Users/lig/Documents/GitHub/NEMESIS/unit_test
切换后的目录： /Users/lig/Documents/GitHub/NEMESIS

In [2]:
import QuantLib as ql
import pandas as pd

from devlib.market.curves.overnight_index_curves import Effr
from devlib.products.rates.irs.general_irs import *

In [3]:
from nemesis.products.rates import *

####################################################################
#  NEMESIS ALPHA Version 0.1.0 - This build: 24 Jan 2025 at 10:42 #
####################################################################

In [4]:
today = ql.Date(17, 12, 2024)
ql.Settings.instance().evaluationDate = today

mkt_file_path = './unit_test/data/effr_curve_data_20241217.xlsx'
swap_mkt_data_1 = pd.read_excel(mkt_file_path, sheet_name='swap')  # only fed funds ois swap
fixing_data = pd.DataFrame()

index_curve = Effr(today, swap_mkt_data=swap_mkt_data_1, fixing_data=fixing_data)
discount_curve = index_curve

In [5]:
value_dt = Date(17,12,2024)
curve = QLCurve(value_dt, index_curve, dc_type=DayCountTypes.ACT_360, interp_type=InterpTypes.LINEAR_ZERO_RATES)

In [6]:
payment_dates = ql_date_to_date(index_curve.curve.dates())[1:]

In [7]:
curve.print_table(payment_dt=payment_dates)

          Date       ZR        DF
0   2024-12-26  4.40045  0.998916
1   2025-01-02  4.39843  0.998074
2   2025-01-09  4.39799  0.997233
3   2025-01-21  4.40034  0.995789
4   2025-02-19  4.38731  0.992337
5   2025-03-19  4.37773  0.989026
6   2025-04-21  4.33851  0.985252
7   2025-05-19  4.31326  0.982082
8   2025-06-20  4.28760  0.978503
9   2025-09-19  4.20881  0.968676
10  2025-12-19  4.14752  0.959155
11  2026-06-24  4.05887  0.940253
12  2026-12-23  4.00809  0.922359
13  2027-12-22  3.94313  0.887955
14  2028-12-21  3.89520  0.855267
15  2029-12-21  3.86565  0.823813
16  2030-12-23  3.84923  0.793190
17  2031-12-23  3.83970  0.763750
18  2032-12-22  3.83556  0.735224
19  2033-12-21  3.83530  0.707649
20  2034-12-21  3.83899  0.680771
21  2036-12-23  3.85639  0.628941
22  2039-12-21  3.87657  0.558652
23  2044-12-21  3.85086  0.462494